-- Minimal seed state only.
--
-- Master, operational, finance, planning, and evaluation data are generated by
-- the deterministic simulation framework. Keeping this file limited to control
-- state avoids two competing authoritative synthetic enterprises in dev/CI.

INSERT INTO operations.simulation_control (
    simulation_id,
    current_simulation_date,
    last_run_at,
    random_seed,
    simulation_speed,
    run_status,
    current_batch_id
) VALUES
    (1, '2024-02-29', NOW(), 424242, 'MONTHLY', 'READY', NULL);
